# Generated by Django 4.2.1 on 2023-06-24 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_FND_Empleado_Cargo',
            fields=[
                ('id_cargo_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'un Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'fnd_empleado_cargo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_operadora_telf',
            fields=[
                ('operadora_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operadora', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'una operadora',
                'verbose_name_plural': 'las operadoras',
                'db_table': 'fnd_operadora_telf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_Parametros_sys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo', models.CharField(max_length=300)),
                ('nombre_contador', models.CharField(max_length=100)),
                ('matricula_contador', models.CharField(max_length=100)),
                ('cedula_rep_legal', models.CharField(max_length=10)),
                ('nombre_rep_legal', models.CharField(max_length=100)),
                ('ced_representante_Creditos', models.CharField(max_length=200)),
                ('nombre_rep_credito', models.CharField(max_length=200)),
                ('fecha_const_fondo', models.DateField()),
                ('correo', models.EmailField(max_length=100)),
                ('smtp_server', models.CharField(max_length=100)),
                ('smtp_port', models.IntegerField()),
                ('smtp_cuenta', models.IntegerField()),
                ('smtp_password', models.TextField(max_length=2000)),
                ('tipo_aportaciion', models.CharField(max_length=1)),
                ('valor_aplicable_aportación', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'un Parametro',
                'verbose_name_plural': 'Parametros',
                'db_table': 'fnd_parametros_sistema',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_Personal',
            fields=[
                ('id_personal', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identificacion', models.CharField(max_length=15, unique=True)),
                ('estado', models.CharField(max_length=3)),
                ('fecha_pago', models.DateField()),
                ('total_ahorrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cargo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_empleado_cargo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'un Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'fnd_personal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_socio',
            fields=[
                ('id_socio', models.BigAutoField(primary_key=True, serialize=False)),
                ('genero', models.CharField(max_length=1)),
                ('estado_civil', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_prestacion', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=3)),
                ('contacto_referencia', models.CharField(max_length=10)),
                ('total_ahorrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_garantizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.CharField(max_length=1000)),
                ('total_creditos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pPresta', models.BooleanField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'fnd_socio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_tipo_descuento',
            fields=[
                ('id_tipo_descuento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_descuento', models.CharField(max_length=100)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'un tipo de descuento',
                'verbose_name_plural': 'Tipos de descuentos',
                'db_table': 'fnd_tipo_descuento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_socio_aportaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aportacion', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_personal')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_socio')),
                ('id_tipo_descuento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_tipo_descuento')),
            ],
            options={
                'verbose_name': 'una aportación',
                'verbose_name_plural': 'Aportaciones',
                'db_table': 'fnd_socio_aportaciones',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_contacto_socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10, unique=True)),
                ('estado', models.BooleanField()),
                ('predeterminado', models.BooleanField(unique=True)),
                ('id_operadora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_operadora_telf')),
                ('id_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_socio')),
            ],
            options={
                'verbose_name': 'un Contacto Socio',
                'verbose_name_plural': 'Contactos Socios',
                'db_table': 'fnd_contacto_socio',
                'managed': True,
            },
        ),
    ]
