# Generated by Django 4.2.1 on 2023-06-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_FND_Empleado_Cargo',
            fields=[
                ('id_cargo_empleado', models.BigAutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'un Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_Parametros_sys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fondo', models.CharField(max_length=300)),
                ('nombre_contador', models.CharField(max_length=100)),
                ('matricula_contador', models.CharField(max_length=100)),
                ('cedula_rep_legal', models.CharField(max_length=10)),
                ('nombre_rep_legal', models.CharField(max_length=100)),
                ('ced_representante_Creditos', models.CharField(max_length=200)),
                ('nombre_rep_Credito', models.CharField(max_length=200)),
                ('fecha_const_fondo', models.DateField()),
                ('correo', models.CharField(max_length=100)),
                ('smtp_server', models.CharField(max_length=100)),
                ('smtp_port', models.IntegerField(max_length=10)),
                ('smtp_cuenta', models.IntegerField(max_length=10)),
                ('smtp_password', models.BinaryField(max_length=2000)),
                ('tipo_Aportaciion', models.CharField(max_length=1)),
                ('valor_aplicable_aportación', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'un Parametro',
                'verbose_name_plural': 'Parametros',
                'db_table': 'parametros',
                'managed': True,
            },
        ),
    ]
