# Generated by Django 4.2.1 on 2023-06-17 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moduloFondo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_FND_Personal',
            fields=[
                ('id_personal', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_ingreso', models.DateField()),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('identificacion', models.CharField(max_length=15, unique=True)),
                ('estado', models.CharField(max_length=3)),
                ('fecha_pago', models.DateField()),
                ('total_ahorrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_cargo_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_empleado_cargo')),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'un Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'FND_Personal',
                'managed': True,
            },
        ),
    ]
