# Generated by Django 4.2.1 on 2023-06-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model_fnd_contacto_socio',
            table='fnd_contacto_socio',
        ),
        migrations.AlterModelTable(
            name='model_fnd_empleado_cargo',
            table='fnd_empleado_cargo',
        ),
        migrations.AlterModelTable(
            name='model_fnd_operadora_telf',
            table='fnd_operadora_telf',
        ),
        migrations.AlterModelTable(
            name='model_fnd_parametros_sys',
            table='fnd_parametros_sistema',
        ),
        migrations.AlterModelTable(
            name='model_fnd_personal',
            table='fnd_personal',
        ),
        migrations.AlterModelTable(
            name='model_fnd_socio',
            table='fnd_socio',
        ),
        migrations.AlterModelTable(
            name='model_fnd_socio_aportaciones',
            table='fnd_socio_aportaciones',
        ),
        migrations.AlterModelTable(
            name='model_fnd_tipo_descuento',
            table='fnd_tipo_descuento',
        ),
    ]
