# Generated by Django 4.2.1 on 2023-06-25 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='ced_representante_Creditos',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='cedula_rep_legal',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='nombre_contador',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='nombre_rep_credito',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='nombre_rep_legal',
        ),
        migrations.AddField(
            model_name='model_fnd_parametros_sys',
            name='contador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contador', to='moduloFondo.model_fnd_socio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_fnd_parametros_sys',
            name='representante_legal',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='representante_legal', to='moduloFondo.model_fnd_socio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model_fnd_parametros_sys',
            name='responsable_creditos',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='responsable_creditos', to='moduloFondo.model_fnd_socio'),
            preserve_default=False,
        ),
    ]
