# Generated by Django 4.2.1 on 2023-06-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_fnd_parametros_sys',
            name='provincia',
            field=models.ForeignKey(choices=[('1', 'Tipo I'), ('2', 'Tipo II'), ('3', 'Tipo III')], on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_provincia'),
        ),
    ]
