# Generated by Django 4.2.1 on 2023-06-25 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model_fnd_operadora_telf',
            table='FND_operadora_telf',
        ),
    ]
