# Generated by Django 4.2.1 on 2023-06-17 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0002_model_fnd_personal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_fnd_parametros_sys',
            name='smtp_cuenta',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='model_fnd_parametros_sys',
            name='smtp_port',
            field=models.IntegerField(),
        ),
    ]
