# Generated by Django 4.2.1 on 2023-06-24 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0002_alter_model_fnd_contacto_socio_table_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_fnd_parametros_sys',
            old_name='nombre_rep_Credito',
            new_name='nombre_rep_credito',
        ),
    ]
