# Generated by Django 4.2.1 on 2023-06-25 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0002_alter_model_fnd_operadora_telf_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model_fnd_operadora_telf',
            table='fnd_operadora_telf',
        ),
    ]
