# Generated by Django 4.2.1 on 2023-06-17 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0003_alter_model_fnd_parametros_sys_smtp_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='model_fnd_empleado_cargo',
            table='FND_Empleado_Cargo',
        ),
        migrations.AlterModelTable(
            name='model_fnd_parametros_sys',
            table='FND_Parametros_sys',
        ),
    ]
