# Generated by Django 4.2.1 on 2023-06-27 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0003_alter_model_fnd_parametros_sys_provincia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='canton',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='email',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='fecha_resolucion',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='identificacion',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='n_resolucion',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='tipo_de_idemtificacion_fcpc',
        ),
        migrations.AlterField(
            model_name='model_fnd_parametros_sys',
            name='provincia',
            field=models.CharField(choices=[('C', 'Para personas naturales identificadas con la cédula de identidad o ciudadanía.'), ('R', 'Para personas naturales o jurídicas identificadas con el número de RUC.'), ('E', 'Para personas naturales o jurídicas identificadas como extranjeras (asignado por la SB).'), ('P', 'PASAPORTE (Artículo 12, Ley de Extranjería) aplica cuentas corrientes y UAF.'), ('X', 'Personas Jurídicas del exterior. (Para las estructuras de Inversiones).')], max_length=300),
        ),
    ]
