# Generated by Django 4.2.1 on 2023-06-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0002_remove_model_fnd_parametros_sys_ced_representante_creditos_and_more'),
        ('moduloFondo', '0003_alter_model_fnd_operadora_telf_table'),
    ]

    operations = [
    ]
