# Generated by Django 4.2.1 on 2023-06-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0003_rename_nombre_rep_credito_model_fnd_parametros_sys_nombre_rep_credito'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_fnd_parametros_sys',
            old_name='tipo_Aportaciion',
            new_name='tipo_aportaciion',
        ),
    ]
