# Generated by Django 4.2.1 on 2023-06-28 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0004_remove_model_fnd_parametros_sys_canton_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='contador',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='fecha_const_fondo',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='matricula_contador',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='nombre_fondo',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='representante_legal',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='responsable_creditos',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='smtp_cuenta',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='smtp_password',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='smtp_port',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='smtp_server',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='tipo_aportaciion',
        ),
        migrations.RemoveField(
            model_name='model_fnd_parametros_sys',
            name='valor_aplicable_aportación',
        ),
        migrations.AlterField(
            model_name='model_fnd_parametros_sys',
            name='provincia',
            field=models.CharField(max_length=300),
        ),
        migrations.DeleteModel(
            name='Model_Fnd_Canton',
        ),
    ]
