# Generated by Django 4.2.1 on 2023-06-17 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moduloFondo', '0005_rename_usuario_id_model_fnd_personal_id_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_FND_operadora_telf',
            fields=[
                ('operadora_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operadora', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'una operadora',
                'verbose_name_plural': 'las operadoras',
                'db_table': 'FND_operadora_telf',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_tipo_descuento',
            fields=[
                ('id_tipo_descuento', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_descuento', models.CharField(max_length=100)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'un tipo de descuento',
                'verbose_name_plural': 'Tipos de descuentos',
                'db_table': 'FND_tipo_descuento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_FND_socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_socio', models.IntegerField()),
                ('genero', models.CharField(max_length=1)),
                ('estado_civil', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField()),
                ('tipo_prestacion', models.CharField(max_length=3)),
                ('estado', models.CharField(max_length=3)),
                ('contacto_referencia', models.IntegerField()),
                ('total_ahorrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_garantizado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.CharField(max_length=1000)),
                ('total_creditos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pPresta', models.BooleanField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'FND_Socio',
                'managed': True,
            },
        ),
    ]
