# Generated by Django 4.2.1 on 2023-06-28 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0005_remove_model_fnd_parametros_sys_contador_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_Fnd_Provincia',
        ),
        migrations.RemoveField(
            model_name='model_fnd_tipo_descuento',
            name='descuento',
        ),
    ]
