# Generated by Django 4.2.1 on 2023-06-17 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0008_model_fnd_socio_aportaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_fnd_parametros_sys',
            name='correo',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_fnd_socio',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
