# Generated by Django 4.2.1 on 2023-06-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloFondo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CNT_Anio_Fiscal',
            fields=[
                ('id_AnioFiscal', models.BigAutoField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.TextField(max_length=3)),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_anio_fiscal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Documentos',
            fields=[
                ('codigo', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('documento', models.TextField(blank=True, max_length=200, null=True, unique=True)),
                ('origen', models.TextField(max_length=1)),
                ('prefijo', models.TextField(blank=True, max_length=5, null=True)),
                ('ultimo_numero', models.IntegerField(default=0, null=True)),
                ('numeracion_automatica', models.BooleanField(default=0)),
                ('activo', models.BooleanField(default=1)),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_documentos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Tipo_Transaccion_Contable',
            fields=[
                ('id_transaccion_contable', models.TextField(max_length=5, primary_key=True, serialize=False)),
                ('tipo_transaccion', models.TextField()),
                ('ultimo_numero', models.IntegerField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_tipotransaccion_contable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Periodo_Fiscal',
            fields=[
                ('id_periodo_fiscal', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.TextField()),
                ('anio_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_anio_fiscal')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_periodo_fiscal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Diario_Cuentas_Plantilla',
            fields=[
                ('id_cuentas_plantillas', models.BigAutoField(primary_key=True, serialize=False)),
                ('identificacador', models.TextField(max_length=500)),
                ('descripcion', models.CharField(max_length=100)),
                ('automatizada', models.BooleanField()),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_documentos')),
                ('transaccion_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_tipo_transaccion_contable')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_diario_cuentas_plantilla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Cuenta_Contable',
            fields=[
                ('codigo_cuenta', models.TextField(primary_key=True, serialize=False)),
                ('nombre_cuenta', models.TextField()),
                ('naturaleza', models.TextField()),
                ('movimiento_mayor', models.TextField()),
                ('nivel', models.SmallIntegerField()),
                ('cuc_reg', models.BooleanField()),
                ('activa', models.BooleanField()),
                ('cuenta_padre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_cuenta_contable')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_cuenta_contable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_Asiento_Contable',
            fields=[
                ('id_asiento_contable', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_documento', models.TextField(max_length=200)),
                ('numero_documento', models.TextField()),
                ('transaccion_contable', models.TextField(max_length=500)),
                ('numero_transaccion', models.TextField(blank=True, max_length=200, null=True)),
                ('nombre_personal', models.TextField(max_length=200)),
                ('nombre_contador', models.TextField(max_length=200)),
                ('nombre_gerente', models.TextField(max_length=200)),
                ('nombre_presidente', models.TextField(max_length=200)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField()),
                ('fecha_mayorización', models.DateTimeField(blank=True, null=True)),
                ('detalle', models.TextField(max_length=500)),
                ('descripcion', models.TextField(blank=True, max_length=500, null=True)),
                ('estado', models.TextField(max_length=3)),
                ('total_debe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_haber', models.DecimalField(decimal_places=2, max_digits=15)),
                ('contador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_personal')),
                ('documeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_documentos')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_personal')),
                ('periodo_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_periodo_fiscal')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_personal')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_diario_cuentas_plantilla')),
                ('presidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloFondo.model_fnd_personal')),
                ('transacción', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_tipo_transaccion_contable')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_Asiento_contable',
                'managed': True,
            },
        ),
    ]
