# Generated by Django 4.2.1 on 2023-06-12 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta_Contable_test',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo', models.TextField(unique=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='moduloContable.cuenta_contable_test')),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'db_table': 'CONTCuenta_Contable',
                'managed': True,
            },
        ),
    ]
