# Generated by Django 4.2.1 on 2023-06-24 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloFondo', '0001_initial'),
        ('moduloContable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='contador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contador', to='moduloFondo.model_fnd_personal'),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='gerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gerente', to='moduloFondo.model_fnd_personal'),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='personal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal', to='moduloFondo.model_fnd_personal'),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='presidente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presidente', to='moduloFondo.model_fnd_personal'),
        ),
        migrations.CreateModel(
            name='Model_CNT_Detalle_plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe_haber', models.CharField(max_length=1)),
                ('cuenta_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_cuenta_contable')),
                ('diario_plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_diario_cuentas_plantilla')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'cnt_detalle_plantilla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Detalle_Asiento_Contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuenta', models.IntegerField()),
                ('detalle', models.CharField()),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('id_asiento_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_asiento_contable')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Detalle_Asiento_Contable',
                'managed': True,
            },
        ),
    ]
