# Generated by Django 4.2.1 on 2023-06-12 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0002_cuenta_contable_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta_contable_model',
            options={'managed': False, 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Cuentas Contables'},
        ),
    ]
