# Generated by Django 4.2.1 on 2023-06-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0002_alter_model_asiento_contable_contador_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model_cnt_detalle_asiento_contable',
            old_name='id_asiento_contable',
            new_name='asiento_contable',
        ),
        migrations.AlterModelTable(
            name='model_cnt_detalle_asiento_contable',
            table='cnt_detalle_asiento_contable',
        ),
    ]
