# Generated by Django 4.2.1 on 2023-06-12 01:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0004_alter_cuenta_contable_model_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cuenta_Contable_test',
        ),
    ]
