# Generated by Django 4.2.1 on 2023-06-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0005_delete_cuenta_contable_test'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cuenta_contable_model',
            table='Cuenta_Contable',
        ),
    ]
