# Generated by Django 4.2.1 on 2023-06-14 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0007_cuenta_contable_model_activo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta_contable_model',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
