# Generated by Django 4.2.1 on 2023-06-14 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0009_factura_producto_factura_productos'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='relacion_producto',
            field=models.ManyToManyField(through='moduloContable.Factura_Productos', to='moduloContable.producto'),
        ),
    ]
