# Generated by Django 4.2.1 on 2023-06-14 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0010_factura_relacion_producto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factura',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='factura_productos',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'managed': True},
        ),
    ]
