# Generated by Django 4.2.1 on 2023-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0011_alter_factura_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='relacion_producto',
        ),
        migrations.RemoveField(
            model_name='factura_productos',
            name='id_factura',
        ),
        migrations.RemoveField(
            model_name='factura_productos',
            name='id_producto',
        ),
        migrations.DeleteModel(
            name='Cuenta_Contable_Model',
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
        migrations.DeleteModel(
            name='Factura_Productos',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
