# Generated by Django 4.2.1 on 2023-06-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloContable', '0012_remove_factura_relacion_producto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Asiento_Contable',
            fields=[
                ('id_AsientoContable', models.BigAutoField(primary_key=True, serialize=False)),
                ('TransaccionContable', models.CharField(max_length=3)),
                ('Numero_Transaccion', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('Documento', models.CharField(max_length=100)),
                ('Numero_Documento', models.CharField(max_length=100)),
                ('Nombre_Persona1', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('Nombre_Representante', models.CharField(max_length=100)),
                ('Total_Debe', models.FloatField()),
                ('Total_Haber', models.FloatField()),
                ('balance', models.FloatField()),
                ('bit', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Asiento_Contable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Anio_Fiscal',
            fields=[
                ('id_AnioFiscal', models.IntegerField(primary_key=True, serialize=False)),
                ('anio', models.IntegerField()),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Anio_Fiscal',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Tipo_Transaccion_Contable',
            fields=[
                ('idTransaccionContable', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipoTransaccion', models.IntegerField()),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Tipo_Transaccion_Contable',
                'managed': True,
            },
        ),
    ]
