# Generated by Django 4.2.1 on 2023-06-17 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0014_model_cnt_cuenta_contable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_Asiento_Contable',
        ),
    ]
