# Generated by Django 4.2.1 on 2023-06-17 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0015_delete_model_asiento_contable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CNT_Periodo_Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_PeriodoFiscal', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Periodo_Fiscal',
                'managed': True,
            },
        ),
    ]
