# Generated by Django 4.2.1 on 2023-06-17 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0016_model_cnt_periodo_fiscal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_CNT_Periodo_Fiscal',
        ),
        migrations.AlterField(
            model_name='model_cnt_anio_fiscal',
            name='id_AnioFiscal',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='model_cnt_anio_fiscal',
            table='Model_CNT_Anio_Fiscal',
        ),
    ]
