# Generated by Django 4.2.1 on 2023-06-17 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0017_delete_model_cnt_periodo_fiscal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CNT_Periodo_Fiscal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_PeriodoFiscal', models.IntegerField()),
                ('numero', models.IntegerField()),
                ('Nombre', models.CharField(max_length=100)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('estado', models.BooleanField()),
                ('anioFiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_anio_fiscal')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Periodo_Fiscal',
                'managed': True,
            },
        ),
    ]
