# Generated by Django 4.2.1 on 2023-06-17 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0018_model_cnt_periodo_fiscal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_Asiento_Contable',
            fields=[
                ('id_AsientoContable', models.BigAutoField(primary_key=True, serialize=False)),
                ('TransaccionContable', models.CharField(max_length=3)),
                ('Numero_Transaccion', models.IntegerField()),
                ('Descripcion', models.CharField(max_length=100)),
                ('Documento', models.CharField(max_length=100)),
                ('Numero_Documento', models.CharField(max_length=100)),
                ('Nombre_Persona1', models.CharField(max_length=100)),
                ('estado', models.BooleanField()),
                ('Nombre_Representante', models.CharField(max_length=100)),
                ('Total_Debe', models.FloatField()),
                ('Total_Haber', models.FloatField()),
                ('balance', models.FloatField()),
                ('bit', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Asiento_Contable',
                'managed': True,
            },
        ),
    ]
