# Generated by Django 4.2.1 on 2023-06-17 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0020_model_cnt_transaccion_contable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CNT_Diario_Cuentas_Plantilla',
            fields=[
                ('idCuentasPlantillas', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=100)),
                ('automatizada', models.BooleanField()),
                ('Cont_Transaccion_Contableid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_transaccion_contable')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Diario_Cuentas_Plantilla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Detalle_plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DebeHaber', models.CharField(max_length=1)),
                ('Cont_Cuenta_ContableCodigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_cuenta_contable')),
                ('Cont_Diario_Plantillaid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_diario_cuentas_plantilla')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Detalle_plantilla',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CNT_Detalle_Asiento_Contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cuenta', models.IntegerField()),
                ('detalle', models.CharField()),
                ('debe', models.FloatField()),
                ('haber', models.FloatField()),
                ('id_asiento_contable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_asiento_contable')),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'CNT_Detalle_Asiento_Contable',
                'managed': True,
            },
        ),
    ]
