# Generated by Django 4.2.1 on 2023-06-21 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0022_rename_descripcion_model_asiento_contable_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_cnt_anio_fiscal',
            name='estado',
        ),
        migrations.AddField(
            model_name='model_cnt_anio_fiscal',
            name='activo',
            field=models.TextField(default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='documento',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='nombre_persona1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='nombre_representante',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='numero_documento',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_asiento_contable',
            name='transaccion_contable',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='model_cnt_cuenta_contable',
            name='movimiento_mayor',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_cnt_cuenta_contable',
            name='naturaleza',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_cnt_cuenta_contable',
            name='nombre_cuenta',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_cnt_detalle_plantilla',
            name='debe_haber',
            field=models.TextField(max_length=1),
        ),
        migrations.AlterField(
            model_name='model_cnt_diario_cuentas_plantilla',
            name='descripcion',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_cnt_periodo_fiscal',
            name='estado',
            field=models.TextField(max_length=3),
        ),
        migrations.AlterField(
            model_name='model_cnt_periodo_fiscal',
            name='nombre',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='model_cnt_tipo_transaccion_contable',
            name='tipo_transaccion',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='model_cnt_transaccion_contable',
            name='detalle',
            field=models.TextField(max_length=100),
        ),
    ]
