# Generated by Django 4.2.1 on 2023-06-21 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloContable', '0023_remove_model_cnt_anio_fiscal_estado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_SIS_Tipo_Documentos',
            fields=[
                ('codigo', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(max_length=3)),
                ('interno_externo', models.TextField()),
                ('prefijo', models.TextField(max_length=100)),
                ('ultimo_numero', models.TextField(max_length=100)),
                ('estado', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un Socio',
                'verbose_name_plural': 'Socios',
                'db_table': 'SIS_Tipo_Documentos',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='model_asiento_contable',
            name='CONT_Diario_PlantillaID',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_diario_cuentas_plantilla'),
        ),
        migrations.AddField(
            model_name='model_asiento_contable',
            name='CONT_Transaccion_ContableCod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_tipo_transaccion_contable'),
        ),
        migrations.AddField(
            model_name='model_asiento_contable',
            name='periodoFiscalId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_cnt_periodo_fiscal'),
        ),
        migrations.AddField(
            model_name='model_asiento_contable',
            name='Sis_Tipo_DocumentosCodigo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_sis_tipo_documentos'),
        ),
        migrations.AddField(
            model_name='model_cnt_diario_cuentas_plantilla',
            name='Sis_Tipo_DocumentosCodigo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='moduloContable.model_sis_tipo_documentos'),
        ),
    ]
