# Generated by Django 4.2.1 on 2023-06-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_core_campos',
            name='id_campo',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
