# Generated by Django 4.2.1 on 2023-06-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_core_tabla',
            name='descripcion',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='model_core_tabla',
            name='ente_provee_tabla',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='model_core_tabla',
            name='numero_tabla',
            field=models.BigIntegerField(null=True),
        ),
    ]
