# Generated by Django 4.2.1 on 2023-06-25 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_model_core_campos_id_campo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_core_campos',
            name='tipo_dato',
        ),
    ]
