# Generated by Django 4.2.1 on 2023-06-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id_socio', models.BigAutoField(primary_key=True, serialize=False)),
                ('cedula', models.CharField(max_length=10)),
                ('nombres', models.CharField(max_length=200, unique=True)),
                ('genero', models.CharField(max_length=3)),
                ('estado_civil', models.CharField(max_length=3)),
                ('direccion', models.CharField(max_length=500)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=16, null=True)),
                ('celular', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'socios',
                'managed': True,
            },
        ),
    ]
