# Generated by Django 4.2.1 on 2023-06-06 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloSocios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cedula',
            field=models.CharField(help_text='Numero de cédula máximo de 10 díjitos', max_length=10),
        ),
    ]
