# Generated by Django 4.2.1 on 2023-06-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloSocios', '0002_alter_socio_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cedula',
            field=models.CharField(help_text='ejemplo: 14102766124', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
