# Generated by Django 4.2.1 on 2023-06-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloSocios', '0003_alter_socio_cedula_alter_socio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='nombres',
            field=models.CharField(max_length=200),
        ),
    ]
