# Generated by Django 4.2.1 on 2023-06-07 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moduloSocios', '0004_alter_socio_cedula_alter_socio_nombres'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'managed': True, 'permissions': [('crear_socio_prms', 'Crear socios'), ('modificar_socio_prms', 'Modificar socios'), ('eliminar_socio_prms', 'Eliminar socios')], 'verbose_name': 'un Socio', 'verbose_name_plural': 'Socios'},
        ),
        migrations.AlterField(
            model_name='socio',
            name='cedula',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cédula'),
        ),
    ]
