# Generated by Django 4.2.1 on 2023-06-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloSocios', '0005_alter_socio_options_alter_socio_cedula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'managed': True, 'permissions': [('crear_socio_prms', 'Crear socios'), ('modificar_socio_prms', 'Modificar socios'), ('eliminar_socio_prms', 'Eliminar socios'), ('ver_socio_prms', 'Ver socios')], 'verbose_name': 'un Socio', 'verbose_name_plural': 'Socios'},
        ),
    ]
