# Generated by Django 4.2.1 on 2023-06-17 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloSocios', '0006_alter_socio_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socio',
            options={'managed': True, 'verbose_name': 'un Socio', 'verbose_name_plural': 'Socios'},
        ),
    ]
