# Generated by Django 4.2.1 on 2023-06-24 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_credito_bien',
            fields=[
                ('id_credito_bien', models.BigAutoField(primary_key=True, serialize=False)),
                ('bien', models.CharField(max_length=200)),
                ('avaluo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('atributos', models.CharField(blank=True, max_length=99999, null=True)),
            ],
            options={
                'verbose_name': 'un crédito por bien',
                'verbose_name_plural': 'créditos por bien',
                'db_table': 'cre_tipo_credito_bien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_bien',
            fields=[
                ('id_tipo_bien', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_bien', models.CharField(max_length=100)),
                ('avaluo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'un tipo de bien',
                'verbose_name_plural': 'tipo de bienes',
                'db_table': 'cre_tipo_bien',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_credito',
            fields=[
                ('id_tipo_credito', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_credito', models.CharField(max_length=100)),
                ('porc_ahorro_acceso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_credito_anios', models.IntegerField()),
                ('prioridad_calif_cartera', models.IntegerField()),
                ('tipo_garan_calif_cartera', models.CharField(max_length=2)),
                ('permite_garante', models.BooleanField()),
                ('gerencia_requerida', models.BooleanField()),
                ('genera_amortizacion', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un tipo de credito',
                'verbose_name_plural': 'tipos de credito',
                'db_table': 'cre_tipo_credito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_montos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_maximo_meses', models.IntegerField()),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una monto del tipo de credito',
                'verbose_name_plural': 'montos de un tipo de credito',
                'db_table': 'cre_tipo_credito_montos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_formato_contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_contable', models.IntegerField()),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una formato contable para tipo de credito',
                'verbose_name_plural': 'formatos contables para tipo de credito',
                'db_table': 'cre_tipo_credito_formato_contable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_docs_requeridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200)),
                ('es_requerido', models.BooleanField()),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'un documento requerido para credito',
                'verbose_name_plural': 'documentos requeridos para credito',
                'db_table': 'cre_tipo_credito_docs_requeridos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una cuenta del tipo de credito',
                'verbose_name_plural': 'cuentas de un tipo de credito',
                'db_table': 'cre_tipo_credito_cuentas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_bien_tipo_credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('id_tipo_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_bien')),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una tipo de bien para credito',
                'verbose_name_plural': 'tipos de bien para creditos',
                'db_table': 'cre_tipo_bien_tipo_credito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_bien_atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(max_length=100)),
                ('obligatorio', models.BooleanField()),
                ('id_tipo_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_bien')),
            ],
            options={
                'verbose_name': 'un atributo de un tipo de bien',
                'verbose_name_plural': 'atributos de un tipo de bien',
                'db_table': 'cre_tipo_bien_atributos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_credito_bien_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200)),
                ('ruta_documento', models.CharField(max_length=1000)),
                ('id_credito_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_credito_bien')),
            ],
            options={
                'verbose_name': 'una solicitud de bien',
                'verbose_name_plural': 'solicitudes de bien',
                'db_table': 'cre_tipo_bien_solicitud',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_bien_documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200)),
                ('ruta_documento', models.CharField(max_length=1000)),
                ('id_bien_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_bien')),
            ],
            options={
                'verbose_name': 'un documento requerido',
                'verbose_name_plural': 'documentos requeridos',
                'db_table': 'cre_bien_documentos',
                'managed': True,
            },
        ),
    ]
