# Generated by Django 4.2.1 on 2023-06-11 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCredito',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_credito', models.TextField(max_length=100, unique=True)),
            ],
        ),
    ]
