# Generated by Django 4.2.1 on 2023-06-21 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Model_CRE_tipo_credito_montos',
        ),
    ]
