# Generated by Django 4.2.1 on 2023-06-25 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_TEST_campos',
            fields=[
                ('id_campo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_campo', models.TextField()),
                ('tipo_dato', models.TextField()),
                ('id_tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_test_tabla')),
            ],
            options={
                'verbose_name': 'un campo',
                'verbose_name_plural': 'campos',
                'db_table': 'test_campo',
                'managed': True,
            },
        ),
    ]
