# Generated by Django 4.2.1 on 2023-06-28 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_TEST_tabla',
            fields=[
                ('id_tabla', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_tabla', models.TextField()),
            ],
            options={
                'verbose_name': 'una tabla',
                'verbose_name_plural': 'tablas',
                'db_table': 'test_tabla',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='model_cre_bien_documentos',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_cre_bien_documentos',
            name='fecha_modificacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_bien',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_bien',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_bien_solicitud',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_bien_solicitud',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_documentos',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_documentos',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_garante',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_garante',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_garante',
            name='genero',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_otorgado',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_otorgado',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_pagos',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_credito_pagos',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_bien',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_bien',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_credito',
            name='fecha_creacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_credito',
            name='fecha_modificacion',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_credito_documentos',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_credito_documentos',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_documentos_bien',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_solicitud_documentos_bien',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien',
            name='es_aceptado',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien_atributo',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien_atributo',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien_documento',
            name='es_requerido',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien_documento',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien_documento',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien_tipo_credito',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_bien_tipo_credito',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_credito',
            name='activo',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_credito',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_credito',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_credito_cuentas',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_credito_cuentas',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_credito_docs_requeridos',
            name='fecha_creacion',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='model_cre_tipo_credito_docs_requeridos',
            name='fecha_modificacion',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='Model_TEST_campos',
            fields=[
                ('id_campo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre_campo', models.TextField()),
                ('tipo_dato', models.TextField()),
                ('id_tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_test_tabla')),
            ],
            options={
                'verbose_name': 'un campo',
                'verbose_name_plural': 'campos',
                'db_table': 'test_campo',
                'managed': True,
            },
        ),
    ]
