# Generated by Django 4.2.1 on 2023-06-21 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model_CRE_tipo_credito_montos',
            new_name='Model_CRE_tipo_credito_monto',
        ),
        migrations.AlterModelOptions(
            name='model_cre_tipo_credito_monto',
            options={'managed': True, 'verbose_name': 'un monto para tipo de credito', 'verbose_name_plural': 'montos para tipo de credito'},
        ),
        migrations.RenameField(
            model_name='model_cre_tipo_credito_monto',
            old_name='plazo_maximo_meses',
            new_name='plazo_meses',
        ),
        migrations.AlterModelTable(
            name='model_cre_tipo_credito_monto',
            table='cre_tipo_credito_monto',
        ),
    ]
