# Generated by Django 4.2.1 on 2023-06-18 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('moduloCreditos', '0002_delete_tipocredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_tipo_bien',
            fields=[
                ('id_tipo_bien', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre_bien', models.CharField(max_length=100)),
                ('avaluo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('observacion', models.TextField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name': 'un tipo de bien',
                'verbose_name_plural': 'tipo de bienes',
                'db_table': 'CRE_tipo_bien',
                'managed': True,
            },
        ),
    ]
