# Generated by Django 4.2.1 on 2023-06-25 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0002_model_test_campos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_TEST_validaciones',
            fields=[
                ('id_validaciones', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_validacion', models.TextField()),
                ('valor_validacion', models.TextField()),
                ('id_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_test_campos')),
            ],
            options={
                'verbose_name': 'una validación',
                'verbose_name_plural': 'validaciones',
                'db_table': 'test_validaciones',
                'managed': True,
            },
        ),
    ]
