# Generated by Django 4.2.1 on 2023-06-18 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_tipo_bien_atributo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.CharField(max_length=100)),
                ('tipo_dato', models.CharField(max_length=100)),
                ('obligatorio', models.BooleanField()),
                ('id_tipo_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_bien')),
            ],
            options={
                'verbose_name': 'un atributo de un tipo de bien',
                'verbose_name_plural': 'atributos de un tipo de bien',
                'db_table': 'CRE_tipo_bien_atributos',
                'managed': True,
            },
        ),
    ]
