# Generated by Django 4.2.1 on 2023-06-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0003_model_test_validaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_TEST_valores',
            fields=[
                ('id_valor', models.BigAutoField(primary_key=True, serialize=False)),
                ('valor', models.TextField()),
                ('id_campo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_test_campos')),
            ],
            options={
                'verbose_name': 'un valor',
                'verbose_name_plural': 'valores',
                'db_table': 'test_valores',
                'managed': True,
            },
        ),
    ]
