# Generated by Django 4.2.1 on 2023-06-19 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0005_alter_model_cre_tipo_bien_table_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_bien_documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200)),
                ('ruta_documento', models.CharField(max_length=1000)),
                ('id_bien_solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_bien')),
            ],
            options={
                'verbose_name': 'un documento requerido',
                'verbose_name_plural': 'documentos requeridos',
                'db_table': 'cre_bien_documentos',
                'managed': True,
            },
        ),
    ]
