# Generated by Django 4.2.1 on 2023-06-19 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0007_model_cre_credito_bien'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_tipo_credito',
            fields=[
                ('id_tipo_credito', models.BigAutoField(primary_key=True, serialize=False)),
                ('tipo_credito', models.CharField(max_length=100)),
                ('porc_ahorro_acceso', models.DecimalField(decimal_places=2, max_digits=3)),
                ('valor_maximo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('max_credito_anios', models.IntegerField()),
                ('prioridad_calif_cartera', models.IntegerField()),
                ('tipo_garan_calif_cartera', models.CharField(max_length=2)),
                ('permite_garante', models.BooleanField()),
                ('gerencia_requerida', models.BooleanField()),
                ('genera_amortizacion', models.BooleanField()),
            ],
            options={
                'verbose_name': 'un tipo de credito',
                'verbose_name_plural': 'tipos de credito',
                'db_table': 'cre_tipo_credito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_docs_requeridos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200)),
                ('es_requerido', models.BooleanField()),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'un documento requerido para credito',
                'verbose_name_plural': 'documentos requeridos para credito',
                'db_table': 'cre_tipo_credito_docs_requeridos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Model_CRE_credito_bien_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_documento', models.CharField(max_length=200)),
                ('ruta_documento', models.CharField(max_length=1000)),
                ('id_credito_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_credito_bien')),
            ],
            options={
                'verbose_name': 'una solicitud de bien',
                'verbose_name_plural': 'solicitudes de bien',
                'db_table': 'cre_tipo_bien_solicitud',
                'managed': True,
            },
        ),
    ]
