# Generated by Django 4.2.1 on 2023-06-19 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0008_model_cre_tipo_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_tipo_bien_tipo_credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField()),
                ('id_tipo_bien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_bien')),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una tipo de bien para credito',
                'verbose_name_plural': 'tipos de bien para creditos',
                'db_table': 'cre_tipo_bien_tipo_credito',
                'managed': True,
            },
        ),
    ]
