# Generated by Django 4.2.1 on 2023-06-19 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0009_model_cre_tipo_bien_tipo_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_montos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_inicial', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_maximo_meses', models.IntegerField()),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una monto del tipo de credito',
                'verbose_name_plural': 'montos de un tipo de credito',
                'db_table': 'cre_tipo_credito_montos',
                'managed': True,
            },
        ),
    ]
