# Generated by Django 4.2.1 on 2023-06-19 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0010_model_cre_tipo_credito_montos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_cuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200, null=True)),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una cuenta del tipo de credito',
                'verbose_name_plural': 'cuentas de un tipo de credito',
                'db_table': 'cre_tipo_credito_cuentas',
                'managed': True,
            },
        ),
    ]
