# Generated by Django 4.2.1 on 2023-06-19 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moduloCreditos', '0011_model_cre_tipo_credito_cuentas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model_CRE_tipo_credito_formato_contable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiento_contable', models.IntegerField()),
                ('id_tipo_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moduloCreditos.model_cre_tipo_credito')),
            ],
            options={
                'verbose_name': 'una formato contable para tipo de credito',
                'verbose_name_plural': 'formatos contables para tipo de credito',
                'db_table': 'cre_tipo_credito_formato_contable',
                'managed': True,
            },
        ),
    ]
